-- Table: usr_sige.aec_vs_export_pipe

-- DROP TABLE IF EXISTS usr_sige.aec_vs_export_pipe;

CREATE TABLE IF NOT EXISTS usr_sige.aec_vs_export_pipe
(
    id integer,
    fk_parent integer,
    fk_function integer,
    fk_installmethod integer,
    fk_material integer,
    fk_distributor integer,
    fk_precision integer,
    fk_bedding integer,
    fk_protection integer,
    fk_status integer,
    fk_watertype integer,
    fk_locationtype integer[],
    fk_folder integer,
    year smallint,
    year_rehabilitation smallint,
    year_end smallint,
    tunnel_or_bridge boolean,
    pressure_nominal smallint,
    remark text COLLATE pg_catalog."default",
    _valve_count smallint,
    _valve_closed boolean,
    schema_force_visible_old boolean,
    label_1_visible smallint,
    label_1_text character varying(120) COLLATE pg_catalog."default",
    label_2_visible smallint,
    label_2_text character varying(120) COLLATE pg_catalog."default",
    fk_node_a integer,
    fk_node_b integer,
    fk_district integer,
    fk_pressurezone integer,
    fk_printmap integer[],
    _length2d numeric(8,2),
    _length3d numeric(8,2),
    _diff_elevation numeric(8,2),
    _printmaps character varying(100) COLLATE pg_catalog."default",
    _geometry_alt1_used boolean,
    _geometry_alt2_used boolean,
    update_geometry_alt1 boolean,
    update_geometry_alt2 boolean,
    geometry geometry(LineStringZ,2056),
    geometry_alt1 geometry(LineStringZ,2056),
    geometry_alt2 geometry(LineStringZ,2056),
    schema_force_visible boolean,
    _schema_visible boolean,
    qwat_ext_ch_vd_sire_etat_exploitation smallint,
    qwat_ext_ch_vd_sire_adesafecter smallint,
    qwat_ext_ch_vd_sire_diametre double precision,
    qwat_ext_ch_vd_sire_remarque text COLLATE pg_catalog."default",
    geometry2d geometry(LineString,2056),
    schema_visible boolean,
    watertype_vl_active boolean,
    watertype_short_fr character varying(10) COLLATE pg_catalog."default",
    watertype_short_en character varying(10) COLLATE pg_catalog."default",
    watertype_short_ro character varying(10) COLLATE pg_catalog."default",
    watertype_value_fr character varying(50) COLLATE pg_catalog."default",
    watertype_value_en character varying(50) COLLATE pg_catalog."default",
    watertype_value_ro character varying(50) COLLATE pg_catalog."default",
    watertype_description_fr text COLLATE pg_catalog."default",
    watertype_description_en text COLLATE pg_catalog."default",
    watertype_description_ro text COLLATE pg_catalog."default",
    watertype_code_sire smallint,
    pipe_material_vl_active boolean,
    pipe_material_short_fr character varying(10) COLLATE pg_catalog."default",
    pipe_material_short_en character varying(10) COLLATE pg_catalog."default",
    pipe_material_short_ro character varying(10) COLLATE pg_catalog."default",
    pipe_material_value_fr character varying(50) COLLATE pg_catalog."default",
    pipe_material_value_en character varying(50) COLLATE pg_catalog."default",
    pipe_material_value_ro character varying(50) COLLATE pg_catalog."default",
    pipe_material_description_fr text COLLATE pg_catalog."default",
    pipe_material_description_en text COLLATE pg_catalog."default",
    pipe_material_description_ro text COLLATE pg_catalog."default",
    pipe_material__displayname_fr character varying(30) COLLATE pg_catalog."default",
    pipe_material__displayname_en character varying(30) COLLATE pg_catalog."default",
    pipe_material__displayname_ro character varying(30) COLLATE pg_catalog."default",
    pipe_material_diameter character varying(10) COLLATE pg_catalog."default",
    pipe_material_diameter_nominal smallint,
    pipe_material_diameter_internal numeric(7,3),
    pipe_material_diameter_external numeric(7,3),
    pipe_material_code_sire smallint,
    pipe_material_pressure_nominal double precision,
    pipe_material_sdr double precision,
    pipe_material_wall_thickness numeric(4,1),
    pipe_material_sn integer,
    precision_vl_active boolean,
    precision_short_fr character varying(10) COLLATE pg_catalog."default",
    precision_short_en character varying(10) COLLATE pg_catalog."default",
    precision_short_ro character varying(10) COLLATE pg_catalog."default",
    precision_value_fr character varying(50) COLLATE pg_catalog."default",
    precision_value_en character varying(50) COLLATE pg_catalog."default",
    precision_value_ro character varying(50) COLLATE pg_catalog."default",
    precision_description_fr text COLLATE pg_catalog."default",
    precision_description_en text COLLATE pg_catalog."default",
    precision_description_ro text COLLATE pg_catalog."default",
    precision_code_sire smallint,
    distributor_name character varying(30) COLLATE pg_catalog."default",
    node_a_fk_district integer,
    node_a_fk_pressurezone integer,
    node_a_fk_printmap integer[],
    node_a__printmaps text COLLATE pg_catalog."default",
    node_a__geometry_alt1_used boolean,
    node_a__geometry_alt2_used boolean,
    node_a__pipe_node_type qwat_od.pipe_connection,
    node_a__pipe_orientation double precision,
    node_a__pipe_schema_visible boolean,
    node_a_update_geometry_alt1 boolean,
    node_a_update_geometry_alt2 boolean,
    district_name character varying(40) COLLATE pg_catalog."default",
    district_shortname character varying(12) COLLATE pg_catalog."default",
    district_zip character varying(12) COLLATE pg_catalog."default",
    district_land_registry character varying(12) COLLATE pg_catalog."default",
    district_prefix character varying(12) COLLATE pg_catalog."default",
    district_colorcode smallint,
    pressurezone_fk_distributor integer,
    pressurezone_fk_consumptionzone integer,
    pressurezone_name character varying(50) COLLATE pg_catalog."default",
    pressurezone_population integer,
    pressurezone_subscriber integer,
    pressurezone_colorcode smallint,
    pressurezone__geometry_alt1_used boolean,
    pressurezone__geometry_alt2_used boolean,
    pressurezone_update_geometry_alt1 boolean,
    pressurezone_update_geometry_alt2 boolean,
    folder_identification character varying(50) COLLATE pg_catalog."default",
    folder_description text COLLATE pg_catalog."default",
    folder_date_start date,
    folder_date_end date,
    folder_authority_approval_identification character varying(50) COLLATE pg_catalog."default",
    folder_authority_approval_description text COLLATE pg_catalog."default",
    folder_to_be_exported_to_authority boolean,
    node_b_fk_district integer,
    node_b_fk_pressurezone integer,
    node_b_fk_printmap integer[],
    node_b__printmaps text COLLATE pg_catalog."default",
    node_b__geometry_alt1_used boolean,
    node_b__geometry_alt2_used boolean,
    node_b__pipe_node_type qwat_od.pipe_connection,
    node_b__pipe_orientation double precision,
    node_b__pipe_schema_visible boolean,
    node_b_update_geometry_alt1 boolean,
    node_b_update_geometry_alt2 boolean,
    pipe_function_vl_active boolean,
    pipe_function_short_fr character varying(10) COLLATE pg_catalog."default",
    pipe_function_short_en character varying(10) COLLATE pg_catalog."default",
    pipe_function_short_ro character varying(10) COLLATE pg_catalog."default",
    pipe_function_value_fr character varying(50) COLLATE pg_catalog."default",
    pipe_function_value_en character varying(50) COLLATE pg_catalog."default",
    pipe_function_value_ro character varying(50) COLLATE pg_catalog."default",
    pipe_function_description_fr text COLLATE pg_catalog."default",
    pipe_function_description_en text COLLATE pg_catalog."default",
    pipe_function_description_ro text COLLATE pg_catalog."default",
    pipe_function_schema_visible boolean,
    pipe_function_major boolean,
    pipe_function_code_sire smallint,
    status_vl_active boolean,
    status_short_fr character varying(10) COLLATE pg_catalog."default",
    status_short_en character varying(10) COLLATE pg_catalog."default",
    status_short_ro character varying(10) COLLATE pg_catalog."default",
    status_value_fr character varying(50) COLLATE pg_catalog."default",
    status_value_en character varying(50) COLLATE pg_catalog."default",
    status_value_ro character varying(50) COLLATE pg_catalog."default",
    status_description_fr text COLLATE pg_catalog."default",
    status_description_en text COLLATE pg_catalog."default",
    status_description_ro text COLLATE pg_catalog."default",
    status_active boolean,
    status_functional boolean,
    status_code_sire smallint,
    protection_vl_active boolean,
    protection_short_fr character varying(10) COLLATE pg_catalog."default",
    protection_short_en character varying(10) COLLATE pg_catalog."default",
    protection_short_ro character varying(10) COLLATE pg_catalog."default",
    protection_value_fr character varying(50) COLLATE pg_catalog."default",
    protection_value_en character varying(50) COLLATE pg_catalog."default",
    protection_value_ro character varying(50) COLLATE pg_catalog."default",
    protection_description_fr text COLLATE pg_catalog."default",
    protection_description_en text COLLATE pg_catalog."default",
    protection_description_ro text COLLATE pg_catalog."default",
    installmethod_vl_active boolean,
    installmethod_short_fr character varying(10) COLLATE pg_catalog."default",
    installmethod_short_en character varying(10) COLLATE pg_catalog."default",
    installmethod_short_ro character varying(10) COLLATE pg_catalog."default",
    installmethod_value_fr character varying(50) COLLATE pg_catalog."default",
    installmethod_value_en character varying(50) COLLATE pg_catalog."default",
    installmethod_value_ro character varying(50) COLLATE pg_catalog."default",
    installmethod_description_fr text COLLATE pg_catalog."default",
    installmethod_description_en text COLLATE pg_catalog."default",
    installmethod_description_ro text COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS usr_sige.aec_vs_export_pipe
    OWNER to sige;
